################################################################
# Date Created: February 2024
# Developer: Brian Clark
# Description: For ETD processing. This file contains 2 
# dictionaries used to map degree to degree type and University
# of Alabama department names to the full authorized form.
#################################################################

degree_dict = {"M.A.":"master’s", "M.S.":"master’s", "M.L.I.S.":"master’s", "M.M.":"master’s", "Ph.D.":"doctoral", "D.M.A.":"doctoral", "Ed.D.":"doctoral", "M.M.S.":"master’s"}

dept_dict = {"Accounting":"Culverhouse School of Accountancy",
"Advertising Public Relations":"University of Alabama. Department of Advertising and Public Relations",
"Aerospace Engineering":"University of Alabama. Department of Aerospace Engineering and Mechanics",
"American Studies":"University of Alabama. Department of American Studies",
"Anthropology":"University of Alabama. Department of Anthropology",
"Applied Mathematics":"University of Alabama. Department of Mathematics",
"Applied Statistics":"University of Alabama. Department of Information Systems, Statistics, and Management Science",
"Art":"University of Alabama. Department of Art and Art History",
"Art History":"University of Alabama. Department of Art and Art History",
"Biological Sciences":"University of Alabama. Department of Biological Sciences",
"Book Arts":"University of Alabama. Department of Library and Information Studies",
"Business Administration":"University of Alabama. Department of Library and Information Studies",
"Chemical & Biological Engineering":"University of Alabama. Department of Chemical and Biological Engineering",
"Chemistry":"University of Alabama. Department of Chemistry and Biochemistry",
"Civil, Construction & Environmental Engineering":"University of Alabama. Department of Civil, Construction, and Environmental Engineering",
"Civil,  Construction & Environmental Engineering":"University of Alabama. Department of Civil, Construction, and Environmental Engineering",
"Cloth Textiles Interior Design":"University of Alabama. Department of Clothing, Textiles, and Interior Design",
"Communication & Information Sciences":"University of Alabama. College of Communication and Information Sciences",
"Communication Studies":"University of Alabama. College of Communication",
"Community Medicine and Population Health":"University of Alabama. Department of Community Medicine and Population Health",
"Computer Science":"University of Alabama. Department of Computer Science",
"Consumer Sciences":"University of Alabama. Department of Consumer Sciences",
"Counselor Education":"University of Alabama. Department of Educational Studies in Psychology, Research Methodology, and Counseling",
"Counselor Education-Community":"University of Alabama. Department of Educational Studies in Psychology, Research Methodology, and Counseling",
"Counselor Education-Rehabilitation Counseling":"University of Alabama. Department of Educational Studies in Psychology, Research Methodology, and Counseling",
"Counselor Education-School Counseling":"University of Alabama. Department of Educational Studies in Psychology, Research Methodology, and Counseling",
"Creative Writing":"University of Alabama. Program in Creative Writing",
"Criminal Justice":"University of Alabama. Department of Criminal Justice",
"Economics (Arts & Sciences)":"University of Alabama. Department of Economics, Finance, and Legal Studies",
"Economics (Business)":"University of Alabama. Department of Economics, Finance, and Legal Studies",
"Educational Administration (Elementary & Middle School)":"University of Alabama. Department of Educational Leadership, Policy, and Technology Studies",
"Educational Administration (Secondary School)":"University of Alabama. Department of Educational Leadership, Policy, and Technology Studies",
"Educational Leadership":"University of Alabama. Department of Educational Leadership, Policy, and Technology Studies",
"Educational Psychology":"University of Alabama. Department of Educational Studies in Psychology, Research Methodology, and Counseling",
"Educational Psychology (General Educational Psychology)":"University of Alabama. Department of Educational Studies in Psychology, Research Methodology, and Counseling",
"Educational Research":"University of Alabama. Department of Educational Studies in Psychology, Research Methodology, and Counseling",
"Educational Research (Educational Psychology)":"University of Alabama. Department of Educational Studies in Psychology, Research Methodology, and Counseling",
"Educational Leadership, Policy, and Technology Studies":"University of Alabama. Department of Electrical and Computer Engineering",
"Electrical and Computer Engineering":"University of Alabama. Department of Educational Leadership, Policy, and Technology Studies",
"Elementary Education":"University of Alabama. Department of Curriculum and Instruction",
"Engineering Science and Mechanics":"University of Alabama. Department of Aerospace Engineering and Mechanics",
"English":"University of Alabama. Department of English",
"English as a Second Language":"University of Alabama. Department of English",
"Environmental Engineering":"University of Alabama. Department of Civil, Construction, and Environmental Engineering",
"Executive Business Administration":"University of Alabama. Department of Civil, Construction, and Environmental Engineering",
"Finance":"University of Alabama. Department of Economics, Finance, and Legal Studies",
"French":"University of Alabama. Department of Modern Languages and Classics",
"Geography":"University of Alabama. Department of Geography",
"Geology":"University of Alabama. Department of Geological Sciences",
"German":"University of Alabama. Department of Modern Languages and Classics",
"Health Education/Promotion":"University of Alabama. Department of Health Science",
"Health Studies":"University of Alabama. Department of Health Science",
"Higher Education Administration":"University of Alabama. Department of Educational Leadership, Policy, and Technology Studies",
"History":"University of Alabama. Department of History",
"Human Development and Family Studies":"University of Alabama. Department of Human Development and Family Studies",
"Human Environmental Sciences, General":"University of Alabama. College of Human Environmental Sciences",
"Human Nutrition":"University of Alabama. Department of Human Nutrition and Hospitality Management",
"Human Performance":"University of Alabama. Department of Kinesiology",
"Instructional Leadership":"University of Alabama. Department of Educational Leadership, Policy, and Technology Studies",
"Interdisciplinary Studies":"University of Alabama. Department of Educational Leadership, Policy, and Technology Studies",
"Journalism":"University of Alabama. Department of Journalism",
"Library and Information Studies":"University of Alabama. School of Library & Information Studies",
"Management":"University of Alabama. Management Department",
"Marine Science":"University of Alabama. Department of Biological Sciences",
"Marketing":"University of Alabama. Department of Marketing",
"Materials Science":"University of Alabama. Department of Physics and Astronomy",
"Mathematics":"University of Alabama. Department of Mathematics",
"Mechanical Engineering":"University of Alabama. Department of Mechanical Engineering",
"Metallurgical/Materials Engineering":"University of Alabama. Department of Metallurgical and Materials Engineering",
"Metallurgical Engineering":"University of Alabama. Department of Metallurgical and Materials Engineering",
"Music":"University of Alabama. School of Music",
"Nursing":"University of Alabama. School of Nursing",
"Operations Management":"University of Alabama. Department of Information Systems, Statistics, and Management Science",
"Physics":"University of Alabama. Department of Physics and Astronomy",
"Political Science":"University of Alabama. Department of Political Science",
"Psychology":"University of Alabama. Department of Psychology",
"Public Adminstration":"University of Alabama. Department of Political Science",
"Religious Studies":"University of Alabama. Department of Religious Studies",
"Romance Languages":"University of Alabama. Department of Modern Languages and Classics",
"School Psychology":"University of Alabama. Department of Educational Studies in Psychology, Research Methodology, and Counseling",
"School Psychology (Educational Psychology)":"University of Alabama. Department of Educational Studies in Psychology, Research Methodology, and Counseling",
"School Psychometry (Educational Psychology)":"University of Alabama. Department of Educational Studies in Psychology, Research Methodology, and Counseling",
"Secondary Education":"University of Alabama. Department of Curriculum and Instruction",
"Social Work":"University of Alabama. School of Social Work",
"Spanish":"University of Alabama. Department of Modern Languages and Classics",
"Special Education":"University of Alabama. Department of Special Education and Multiple Abilities",
"Special Education":"University of Alabama. Department of Special Education and Muliple Abilities",
"Speech Language Pathology":"University of Alabama. Department of Communicative Disorders",
"Tax Accounting":"Culverhouse School of Accountancy",
"Telecommunication and Film":"University of Alabama. Department of Telecommunication and Film",
"Theatre":"University of Alabama. Department of Theatre and Dance",
"Women's Studies":"University of Alabama. Department of Gender and Race Studies"}